### ISSUE TITLE
timeout is not working

### ISSUE THREAD

**Issue by intoxicated** [thom-nic/python-xbee#1]
wait_read_frame(timeout=x) is not working at all

**Comment by thom-nic** [comment]
Just posted this to the code.google.com issue but I'll repost here...

you need to setup the underlying serial connection so that the `read()` call won't block.  Otherwise, yes, `self.serial.read()` will still hang.  Here's an example of what we're doing:

``` python
self.xbee = xbee.DigiMesh( ser= {
            'port': tty,
            'baudrate' : BAUD, 
            'timeout' : TIMEOUT },
            escaped = False, 
            callback = self.callback )
```

That `'timeout'` param is what will prevent `serial.read()` from blocking.  It just loops if it doesn't get any bytes before the serial timeout but it allows the thread to exit cleanly when `halt` is called.
